# Base scores
BASE_MARKET_SCORE = 60
BASE_CUSTOMER_SCORE = 60
BASE_COMPETITION_SCORE = 70
BASE_RISK_SCORE = 80
BASE_EXECUTION_SCORE = 60
BASE_GTM_SCORE = 60

# Score modifiers
MARKET_MATURITY_BONUS = 15
MARKET_OPPORTUNITY_MULTIPLIER = 5
MARKET_CHALLENGE_PENALTY = 2

CUSTOMER_SEGMENT_MULTIPLIER = 5
CUSTOMER_PAIN_POINT_MULTIPLIER = 5

COMPETITOR_PENALTY_MULTIPLIER = 5
COMPETITOR_GAP_BONUS = 15

RISK_TOP_RISK_PENALTY = 10
RISK_STANDARD_RISK_PENALTY = 2
RISK_LEVEL_HIGH_PENALTY = 20
RISK_LEVEL_LOW_BONUS = 10

EXECUTION_FEATURE_MULTIPLIER = 5
GTM_CHANNEL_MULTIPLIER = 5
GTM_HACK_MULTIPLIER = 5

# Confidence bonuses
CONFIDENCE_HIGH_BONUS_10 = 10
CONFIDENCE_HIGH_BONUS_15 = 15
CONFIDENCE_HIGH_BONUS_5 = 5

# Verdict Thresholds
VERDICT_EXCEPTIONAL_THRESHOLD = 90
VERDICT_PROMISING_THRESHOLD = 75
VERDICT_MODERATE_THRESHOLD = 60
VERDICT_HIGH_RISK_THRESHOLD = 40
