import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Download, Sparkles, Loader2, Plus, Check } from 'lucide-react';
import { useDashboardData } from '../../contexts/DashboardContext';
import { useWorkspaceActions } from '../../hooks/useWorkspaceActions';
import { useLocation } from 'react-router-dom';

const DashboardActions = () => {
  const navigate = useNavigate();
  const { data, requestId, idea, handleExport } = useDashboardData();
  const [isExporting, setIsExporting] = React.useState(false);

  const location = useLocation();
  const currentPath = location.pathname.split('/').pop();
  const isAgentPage = ['research', 'market', 'customer', 'competitor', 'risk', 'swot', 'mvp', 'gtm'].includes(currentPath);

  const { handleAddTask, isAddingTask } = useWorkspaceActions(requestId || data?.metadata?.request_id, idea);
  const [showToast, setShowToast] = React.useState(false);

  const onExportPdfClick = async () => {
    setIsExporting(true);
    let exportData = data;
    
    // If it's an agent page, nullify the other agents to restrict the export scope
    if (isAgentPage) {
      const agentKeyMap = {
        'market': 'market_agent',
        'customer': 'customer_agent',
        'competitor': 'competitor_agent',
        'risk': 'risk_agent',
        'swot': 'swot_agent',
        'mvp': 'mvp_agent',
        'gtm': 'gtm_agent',
        'research': 'research_agent' // Though research might not be in pdf directly
      };
      
      exportData = { ...data };
      
      // Nullify everything except the executive summary and the active agent
      Object.keys(agentKeyMap).forEach(key => {
        if (key !== currentPath && exportData[agentKeyMap[key]]) {
          exportData[agentKeyMap[key]] = null;
        }
      });
    }

    await handleExport(idea, exportData, 'pdf');
    setIsExporting(false);
  };

  const onExportPptClick = async () => {
    setIsExporting(true);
    await handleExport(idea, data, 'ppt');
    setIsExporting(false);
  };

  const onAddToWorkspaceClick = async () => {
    const success = await handleAddTask(
      `${currentPath.toUpperCase()} Agent Insights`,
      `Review and execute the insights generated by the ${currentPath} agent.`,
      { source: currentPath }
    );
    if (success) {
      setShowToast(true);
      setTimeout(() => setShowToast(false), 3000);
    }
  };

  const onVeraClick = () => {
    navigate('/vera', { state: { sessionId: requestId || data?.metadata?.request_id } });
  };

  return (
    <div className="mt-8 flex justify-between items-center bg-surface/30 p-6 rounded-2xl border border-white/5">
      <div className="flex gap-4">
        <button
          onClick={onExportPdfClick}
          disabled={isExporting}
          className="flex items-center gap-2 px-6 py-3 bg-surface hover:bg-surface/80 border border-border rounded-xl transition-all"
        >
          {isExporting ? <Loader2 className="w-5 h-5 text-textMuted animate-spin" /> : <Download className="w-5 h-5 text-textMuted" />}
          <span className="font-medium">Export PDF</span>
        </button>
        
        {!isAgentPage && (
          <button
            onClick={onExportPptClick}
            disabled={isExporting}
            className="flex items-center gap-2 px-6 py-3 bg-surface hover:bg-surface/80 border border-border rounded-xl transition-all"
          >
            {isExporting ? <Loader2 className="w-5 h-5 text-textMuted animate-spin" /> : <Download className="w-5 h-5 text-textMuted" />}
            <span className="font-medium">Export Pitch Deck</span>
          </button>
        )}
      </div>
      
      {isAgentPage ? (
        <button
          onClick={onAddToWorkspaceClick}
          disabled={isAddingTask}
          className="flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-emerald-600 to-teal-600 text-white font-medium rounded-xl hover:from-emerald-500 hover:to-teal-500 transition-all shadow-lg shadow-emerald-500/25 relative"
        >
          {showToast ? (
            <>
              <Check className="w-5 h-5" />
              <span>Added to Workspace!</span>
            </>
          ) : (
            <>
              {isAddingTask ? <Loader2 className="w-5 h-5 animate-spin" /> : <Plus className="w-5 h-5" />}
              <span>Add to Workspace</span>
            </>
          )}
        </button>
      ) : (
        <button
          onClick={onVeraClick}
          className="flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-blue-600 to-indigo-600 text-white font-medium rounded-xl hover:from-blue-500 hover:to-indigo-500 transition-all shadow-lg shadow-blue-500/25"
        >
          <Sparkles className="w-5 h-5" />
          <span>Open AI Co-Founder Workspace</span>
        </button>
      )}
    </div>
  );
};

export default React.memo(DashboardActions);
