"""Update foreign keys and add TaskProgress

Revision ID: 589bacca612a
Revises: bbeebb0f496d
Create Date: 2026-08-24 17:32:37.200165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '589bacca612a'
down_revision: Union[str, Sequence[str], None] = 'bbeebb0f496d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_progress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_progress_status'), 'task_progress', ['status'], unique=False)
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'reports', ['report_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'reports', ['report_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'telemetry_logs', type_='foreignkey')
    op.drop_constraint(None, 'telemetry_logs', type_='foreignkey')
    op.create_foreign_key(None, 'telemetry_logs', 'reports', ['report_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'telemetry_logs', 'chat_sessions', ['session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telemetry_logs', type_='foreignkey')
    op.drop_constraint(None, 'telemetry_logs', type_='foreignkey')
    op.create_foreign_key(None, 'telemetry_logs', 'reports', ['report_id'], ['id'])
    op.create_foreign_key(None, 'telemetry_logs', 'chat_sessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'reports', ['report_id'], ['id'])
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'reports', ['report_id'], ['id'])
    op.drop_index(op.f('ix_task_progress_status'), table_name='task_progress')
    op.drop_table('task_progress')
    # ### end Alembic commands ###
